version: "3.7"
services:
  nginx:
    image: chaberb/nginx-ssl
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf
      - ./polaczek.odas.com.crt:/etc/nginx/polaczek.odas.com.crt
      - ./polaczek.odas.com.key:/etc/nginx/polaczek.odas.com.key
    depends_on:
      - web
  web:
    build: .
    env_file:
      - ./.env.prod
    environment:
      - FLASK_APP=app
    depends_on:
      - db
    volumes:
      - ./app:/var/www/app
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=odas
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined
